COMMENT ON COLUMN "KT_ABIC"."BH_BA_CT_TP"."TTRANG" IS '0: da yeu cau va ko nhan dc phan hoi; 00: da yeu cau thanh cong; 000: da doi soat thanh cong;
   444: yeu cau thu phi trung hieu luc bao hiem; 0000: da kiem soat; khac: da yeu cau va tra ve ma loi.';
COMMENT ON COLUMN "KT_ABIC"."HT_NSD_TK"."LOAI" IS '1:PMNV, 2. Email, 3. Van ban, 4. Chuyen tien, 6. Dien thoai';
COMMENT ON COLUMN "KT_ABIC"."BH_DL_CN_TON"."SO_ID" IS 'So id chung tu phat sinh';
COMMENT ON COLUMN "KT_ABIC"."BH_DL_CN_TON"."SO_CT" IS 'So chung tu phat sinh (so_hd hoac so_bk)';
COMMENT ON COLUMN "KT_ABIC"."BH_DL_CN_TON"."SO_TC" IS 'So chung tu tham chieu';
COMMENT ON COLUMN "KT_ABIC"."HT_NSD"."LOAI" IS '1:Can bo ABIC, 2: Dai ly, 3: Khach hang, 4,5: NHNo, 6: Mobile App''s Users';
COMMENT ON COLUMN "KT_ABIC"."HT_NSD"."TTRANG" IS '1:Dang hoat dong, 0: Khong hoat dong';
COMMENT ON COLUMN "KT_ABIC"."HT_NSD"."TGIAN" IS 'Thoi gian dang nhap gan nhat';
COMMENT ON TABLE "KT_ABIC"."ERR$_BH_HDDT_HHDV_NEW"  IS 'DML Error Logging table for "BH_HDDT_HHDV_NEW"';
COMMENT ON COLUMN "KT_ABIC"."QT_XL"."PBAN_QT" IS 'Pin version workflow luc tao - HD chay xong voi version cu, HD moi dung version moi';
COMMENT ON COLUMN "KT_ABIC"."QT_XL"."TTRANG_QT" IS 'Vong doi QT: DANG_CHAY (active) / TAM_DUNG (admin treo) / HOAN_TAT / DA_HUY';
COMMENT ON COLUMN "KT_ABIC"."QT_XL"."TTRANG_BUOC" IS 'Pha buoc hien tai: CHO_XL (queue-wait) / DANG_XL (worker chay) / CHO_NSD (manual) / LOI / XONG';
COMMENT ON TABLE "KT_ABIC"."QT_XL"  IS 'Instance quy trinh dang chay - hot table, DELETE boi cron sau 7 ngay khi dong';
COMMENT ON COLUMN "KT_ABIC"."HT_NSD_LK_LS"."LOAI" IS 'Loai thay doi: phong; ma_kh; ma_dl; ma_nh; matkhau;..';
COMMENT ON COLUMN "KT_ABIC"."HT_NSD_LK_LS"."TT" IS 'Thong tin tham chieu ve su thay doi.';
COMMENT ON COLUMN "KT_ABIC"."HT_NSD_LK_LS"."NSD" IS 'NSD thuc hien thay doi';
COMMENT ON TABLE "KT_ABIC"."HT_NSD_LK_LS"  IS 'Lich su thay doi lien ket giua NSD va to chuc';
COMMENT ON COLUMN "KT_ABIC"."QT_CHUYEN"."TTIN" IS 'JSON: {sp_dk, tdong, quyen} - sp_dk NULL = default branch';
COMMENT ON TABLE "KT_ABIC"."QT_CHUYEN"  IS 'Dinh nghia chuyen doi hop le giua cac buoc (edge cua state machine)';
COMMENT ON COLUMN "KT_ABIC"."QT_BUOC"."CUOI" IS 'NULL=trung gian; OK=terminal thanh cong -> ttrang_qt=HOAN_TAT; HUY=terminal huy -> ttrang_qt=DA_HUY';
COMMENT ON COLUMN "KT_ABIC"."QT_BUOC"."SP_XL" IS 'Handler SP nghiep vu, signature chuan: (p_so_id_qt RAW)';
COMMENT ON COLUMN "KT_ABIC"."QT_BUOC"."TTIN" IS 'JSON: {timeout, retry, delay, backoff, max_delay, jitter, thucong, sp_ktra, chay_sau_gio, gian_phut}. chay_sau_gio=N: chi enqueue buoc sau N gio trong ngay (vd 16); gian_phut=M: rai random 0..M phut chong don.';
COMMENT ON TABLE "KT_ABIC"."QT_BUOC"  IS 'Dinh nghia cac buoc (node) cua workflow';
COMMENT ON COLUMN "KT_ABIC"."HT_NSD_LK"."MA_CV" IS 'Ma chuc vu';
COMMENT ON COLUMN "KT_ABIC"."HT_NSD_LK"."MA_NH" IS 'Ma ngan hang';
COMMENT ON TABLE "KT_ABIC"."HT_NSD_LK"  IS 'Luu thong tin lien ket giua NSD va to chuc';
COMMENT ON COLUMN "KT_ABIC"."QT_LOI_PS"."TTRANG_TRUOC" IS 'ttrang_loi cua QT_LOI truoc event (NULL neu LOI_PS lan dau)';
COMMENT ON COLUMN "KT_ABIC"."QT_LOI_PS"."TTRANG_SAU" IS 'ttrang_loi cua QT_LOI sau event (engine update QT_LOI cung trong 1 tx)';
COMMENT ON TABLE "KT_ABIC"."QT_LOI_PS"  IS 'Event log (insert-only, append-only) cho QT_LOI. Audit trail moi state change.';
COMMENT ON COLUMN "W_ABIC"."HOSO"."HOSO_ID" IS 'H¿ so con (Trên phân c¿p)';
COMMENT ON COLUMN "KT_ABIC"."HT_NHOM"."LOAI" IS '1:Don vi; 2:Phong, ban; 3:Khac; 0:NSD tao';
COMMENT ON COLUMN "KT_ABIC"."QT_LOI"."NOI_DUNG" IS 'Latest message - denorm cho dashboard. History day du o QT_LOI_PS.';
COMMENT ON COLUMN "KT_ABIC"."QT_LOI"."SO_LAN_PS" IS 'Counter derive tu QT_LOI_PS WHERE loai_ps=LOI_PS. Engine UPSERT tang khi handler fail';
COMMENT ON TABLE "KT_ABIC"."QT_LOI"  IS 'Issue aggregate. 1 row per (so_id_qt, buoc_loi). UPSERT counter. Event detail o QT_LOI_PS.';
COMMENT ON COLUMN "W_ABIC"."WF_TTHAI"."CBO_CUNG_DVI" IS 'Yeu cau can bo cung dvi voi ma dvi cua ho so';
COMMENT ON COLUMN "W_ABIC"."WF_TTHAI"."HTHI_TTIN" IS 'Hien thi thong tin ve cong viec cua can bo';
COMMENT ON COLUMN "W_ABIC"."WF_TTHAI"."CP_UNDO" IS 'Cho phep undo';
COMMENT ON COLUMN "W_ABIC"."WF_TTHAI"."CP_CHUYEN" IS 'Cho phep chuyen tu ben ngoai khong can vao quy trinh';
COMMENT ON COLUMN "W_ABIC"."WF_TTHAI"."CP_MAIL" IS 'Cho phep gui mail';
COMMENT ON COLUMN "KT_ABIC"."QT_LS"."BUOC_TRUOC" IS 'Chi co gia tri khi loai_ls=KD_BUOC - cho phep query transition A->B khong can self-join';
COMMENT ON COLUMN "KT_ABIC"."QT_LS"."IDEM_KEY" IS 'Cho NSD_XNHAN events - chong double-submit. Cron purge sau 7 ngay (set NULL)';
COMMENT ON TABLE "KT_ABIC"."QT_LS"  IS 'Lich su hoat dong QT (event log immutable). Giu lau hon QT_XL.';
exit