   CREATE PROFILE "APP_USERS"
    LIMIT
         COMPOSITE_LIMIT UNLIMITED
         SESSIONS_PER_USER UNLIMITED
         CPU_PER_SESSION UNLIMITED
         CPU_PER_CALL UNLIMITED
         LOGICAL_READS_PER_SESSION UNLIMITED
         LOGICAL_READS_PER_CALL UNLIMITED
         IDLE_TIME UNLIMITED
         CONNECT_TIME UNLIMITED
         PRIVATE_SGA UNLIMITED
         FAILED_LOGIN_ATTEMPTS 3
         PASSWORD_LIFE_TIME 31536000/86400
         PASSWORD_REUSE_TIME 15552000/86400
         PASSWORD_REUSE_MAX 10
         PASSWORD_VERIFY_FUNCTION "DBA_PASSWORD_VERIFY_FUNCTION"
         PASSWORD_LOCK_TIME 86400/86400
         PASSWORD_GRACE_TIME 604800/86400
         INACTIVE_ACCOUNT_TIME DEFAULT
         PASSWORD_ROLLOVER_TIME DEFAULT;

   CREATE PROFILE "DEV_USERS"
    LIMIT
         COMPOSITE_LIMIT UNLIMITED
         SESSIONS_PER_USER 8
         CPU_PER_SESSION UNLIMITED
         CPU_PER_CALL UNLIMITED
         LOGICAL_READS_PER_SESSION UNLIMITED
         LOGICAL_READS_PER_CALL UNLIMITED
         IDLE_TIME 30
         CONNECT_TIME UNLIMITED
         PRIVATE_SGA UNLIMITED
         FAILED_LOGIN_ATTEMPTS 3
         PASSWORD_LIFE_TIME 5184000/86400
         PASSWORD_REUSE_TIME 15552000/86400
         PASSWORD_REUSE_MAX 10
         PASSWORD_VERIFY_FUNCTION "DEV_PASSWORD_VERIFY_FUNCTION"
         PASSWORD_LOCK_TIME 86400/86400
         PASSWORD_GRACE_TIME 604800/86400
         INACTIVE_ACCOUNT_TIME DEFAULT
         PASSWORD_ROLLOVER_TIME DEFAULT;
exit
