############################################################
#Source database properties
# -
# - ORACLE_HOME     Path to Oracle Home Directory
# - ORACLE_SID      SID of the source database
# - SRC_SCAN        Connect string to source database via SCAN.
#                   If no SCAN, specify source database network name.
#                   Enclose in single quotes
#                      Example: 'myhost-scan/db1'
#                      Example: 'localhost/pdb1'
# - PDB_NAME        If source is a PDB, specify PDB name.
#                   Else leave blank
#                      Example: PDB1
# - BKP_FROM_STDBY  Accepted values: 0, 1
#                      Choose 0 to back up from primary database,
#                      or if Data Guard is not in use.
#                      Choose 1 to back up from standby database.
# - REMOVE_TS_QUOTE Accepted values: 0, 1
#                      Default 1
#                      Choose 0 to keep double quote
#                      Choose 1 to remove double quote
# - RMAN_SCAN   Accepted values: Connect string for CDB/NON-CDN
#                      Default Blank
#                      BLANK : No channel distribution use target / and prompt for password
#                      VALUE:  Use value as scan for target /@<RMAN_SCAN> and no-prompt
#                              Will distribute channels across nodes
#                              Also enforces SEPS for both the SRC_SCAN and RMAN_SCAN, SYSTEM_USR is ignored
############################################################
export ORACLE_HOME=/u01/app/oracle/product/19c/dbhome_1
export PATH=$PATH:$ORACLE_HOME/bin
export ORACLE_SID=cmis3bc
export SRC_SCAN='db-baocao:1522/cmis3'
export PDB_NAME=
export BKP_FROM_STDBY=0
export REMOVE_TS_QUOTE=1
export RMAN_SCAN=
############################################################
#Source Data Pump settings
# - SOURCE_DPDMP    Directory path of the directory DATA_PUMP_DIR
#                      Example: /u01/app/oracle/m5/data_pump_dir
# - SOURCE_DPDIR     Data Pump Directory, typically DATA_PUMP_DIR
# - SYSTEM_USR      Username for Data Pump export.
#                   Do not use SYS AS SYSDBA
#                      Example: SYSTEM
#                   If using RMAN_SCAN, this value is ignored
# - DP_TRACE        Data Pump trace level.
#                   Use 0 to disable trace.
#                   Use 3FF0300 to full transportable tracing
#                   See MOS Doc ID 286496.1 for details.
# - DP_PARALLEL     Data Pump parallel setting.
#                   Accepted values: 1 to 999
#                      Example: 16
# - DP_ENC_PROMPT   Accepted values N/Y, default is N
#                   If set to Y, "ENCRYPTION_PWD_PROMPT=YES" will be added to datapump export parameter file
############################################################
export SOURCE_DPDMP=/u01/app/oracle/m5/data_pump_dir
export SOURCE_DPDIR=DATA_PUMP_DIR
export SYSTEM_USR=SYSTEM
export DP_TRACE=0
export DP_PARALLEL=1
export DP_ENC_PROMPT=N
############################################################
#Source RMAN settings
# - BKP_DEST_TYPE   Accepted values: DISK, SBT_TAPE
#                      Choose DISK to backup up to local storage
#                      Choose SBT_TAPE to use ZDLRA
# - BKP_DEST_PARM   If BKP_DEST_TYPE=DISK, enter location for backup:
#                      Example: /u01/app/oracle/m5/rman
#                   If BKP_DEST_TYPE=SBT_TAPE, enter channel configuration:
#                      Example: "'%d_%U' PARMS \"SBT_LIBRARY=<oracle_home>/lib/libra.so,SBT_PARMS=(RA_WALLET='location=file:<oracle_home>/dbs/zdlra credential_alias=<zdlra-connect-string>')\""
# - CAT_CRED        If you use RMAN catalog or ZDLRA, specify connect string to catalog database
#                      Example: <scan-name>:<port>/<service>
# - SECTION_SIZE    Section size used in RMAN backups
# - CHN             Number of RMAN channels allocated
# - RMAN_DEBUG      Accepted values N/Y, default is N
#                   Adds "debug trace" to rman execution, trace is logged to TRC_LOG
############################################################
export BKP_DEST_TYPE=SBT_TAPE
export BKP_DEST_PARM="'%d_%U' PARMS \"SBT_LIBRARY=/u01/app/oracle/product/19c/dbhome_1/lib/libra.so, SBT_PARMS=(_RA_NO_SSL=TRUE,RA_WALLET='location=file:/u01/app/oracle/product/19c/dbhome_1/dbs/zdlra credential_alias=zdl0db-scan1:1521/zdl0db:dedicated')\""
export CAT_CRED=VPC_TONGHOP/oracle_4U@zdl0db-scan1:1521/zdl0db
export SECTION_SIZE=64G
export CHN=16
export RMAN_DEBUG=N
############################################################
#Destination host settings
#If specified, the script transfers the RMAN backups and
#Data Pump dump file to the destination via over SSH.
#SSH equivalence is required.
# - DEST_SERVER     Network name of the destination server.
#                   Leave blank if you manually transfer
#                   backups and dump files
# - DEST_USER       User for SSH connection
#                      Example: oracle
# - DEST_WORKDIR    The script working directory on destination
#                      Example: /u01/app/oracle/m5
# - DEST_DPDMP      The directory path used by DATA_PUMP_DIR
#                   in destination database
#                      Example: /u01/app/oracle/m5/data_pump_dir
############################################################
export DEST_SERVER=dbcmisbc01-clu01
export DEST_USER=oracle
export DEST_WORKDIR=/u01/app/oracle/m5
export DEST_DPDMP=/u01/app/oracle/m5/data_pump_dir

############################################################
#Advanced settings
#Normally, you don't need to edit this section
############################################################
export WORKDIR=$PWD
export LOG_DIR=${WORKDIR}/log
export CMD_DIR=${WORKDIR}/cmd
export PATH=$PATH:$ORACLE_HOME/bin
export DT=`date +%y%m%d%H%M%S`
export CMD_MKDIR=`which mkdir`
export CMD_TOUCH=`which touch`
export CMD_CAT=`which cat`
export CMD_RM=`which rm`
export CMD_AWK=`which awk`
export CMD_SCP=`which scp`
export CMD_CUT=`which cut`
export CMD_PLATFORM=`uname`
if [[ "$CMD_PLATFORM" = "Linux" ]]; then
    export CMD_GREP="/usr/bin/grep"
else
    if [[ "$CMD_PLATFORM" = "AIX" ]]; then
      export CMD_GREP="/usr/bin/grep"
    else
      if [[ "$CMD_PLATFORM" = "HPUX" ]]; then
        export CMD_GREP="/usr/bin/grep"
      else
        export CMD_GREP=`which ggrep`
      fi
    fi
fi
export my_M5_prop_version=5