/* ==================================== */
/* Make all user tablespaces READ WRITE */
/* ==================================== */

ALTER TABLESPACE USERS READ WRITE;
ALTER TABLESPACE OWACQ_D READ WRITE;
ALTER TABLESPACE OWACQ_I READ WRITE;
ALTER TABLESPACE OWCOMS_D READ WRITE;
ALTER TABLESPACE OWCOMS_I READ WRITE;
ALTER TABLESPACE OWCONST_D READ WRITE;
ALTER TABLESPACE OWCONST_I READ WRITE;
ALTER TABLESPACE OWCONTR_D READ WRITE;
ALTER TABLESPACE OWCONTR_I READ WRITE;
ALTER TABLESPACE OWDOC_D READ WRITE;
ALTER TABLESPACE OWDOC_I READ WRITE;
ALTER TABLESPACE OWFIN_D READ WRITE;
ALTER TABLESPACE OWFIN_I READ WRITE;
ALTER TABLESPACE OWLARGE_D READ WRITE;
ALTER TABLESPACE OWLARGE_I READ WRITE;
ALTER TABLESPACE OWMEDIUM_D READ WRITE;
ALTER TABLESPACE OWMEDIUM_I READ WRITE;
ALTER TABLESPACE OWRPL_D READ WRITE;
ALTER TABLESPACE OWRPL_I READ WRITE;
ALTER TABLESPACE OWSTATIC_D READ WRITE;
ALTER TABLESPACE OWSTATIC_I READ WRITE;
ALTER TABLESPACE OWSTATLARGE_D READ WRITE;
ALTER TABLESPACE OWSTATLARGE_I READ WRITE;
ALTER TABLESPACE OWSREP_TB READ WRITE;
ALTER TABLESPACE OWSAPI_TBS READ WRITE;
