/* =================================== */
/* Make all user tablespaces READ ONLY */
/* =================================== */

ALTER TABLESPACE USERS READ ONLY;
ALTER TABLESPACE OWACQ_D READ ONLY;
ALTER TABLESPACE OWACQ_I READ ONLY;
ALTER TABLESPACE OWCOMS_D READ ONLY;
ALTER TABLESPACE OWCOMS_I READ ONLY;
ALTER TABLESPACE OWCONST_D READ ONLY;
ALTER TABLESPACE OWCONST_I READ ONLY;
ALTER TABLESPACE OWCONTR_D READ ONLY;
ALTER TABLESPACE OWCONTR_I READ ONLY;
ALTER TABLESPACE OWDOC_D READ ONLY;
ALTER TABLESPACE OWDOC_I READ ONLY;
ALTER TABLESPACE OWFIN_D READ ONLY;
ALTER TABLESPACE OWFIN_I READ ONLY;
ALTER TABLESPACE OWLARGE_D READ ONLY;
ALTER TABLESPACE OWLARGE_I READ ONLY;
ALTER TABLESPACE OWMEDIUM_D READ ONLY;
ALTER TABLESPACE OWMEDIUM_I READ ONLY;
ALTER TABLESPACE OWRPL_D READ ONLY;
ALTER TABLESPACE OWRPL_I READ ONLY;
ALTER TABLESPACE OWSTATIC_D READ ONLY;
ALTER TABLESPACE OWSTATIC_I READ ONLY;
ALTER TABLESPACE OWSTATLARGE_D READ ONLY;
ALTER TABLESPACE OWSTATLARGE_I READ ONLY;
ALTER TABLESPACE OWSREP_TB READ ONLY;
ALTER TABLESPACE OWSAPI_TBS READ ONLY;
