/* =================================== */
/* Make all user tablespaces READ ONLY */
/* =================================== */

ALTER TABLESPACE USERS READ ONLY;
ALTER TABLESPACE FCCDATALAR READ ONLY;
ALTER TABLESPACE FCCDATAMED READ ONLY;
ALTER TABLESPACE FCCDATASML READ ONLY;
ALTER TABLESPACE FCCDATAXL READ ONLY;
ALTER TABLESPACE FCCINDXLAR READ ONLY;
ALTER TABLESPACE FCCINDXMED READ ONLY;
ALTER TABLESPACE FCCINDXSML READ ONLY;
ALTER TABLESPACE FCCINDXXL READ ONLY;
ALTER TABLESPACE FCAT_PRD READ ONLY;
ALTER TABLESPACE TBS_IDX_LOGDATA_PRD READ ONLY;
ALTER TABLESPACE TBS_LOGDATA_PRD READ ONLY;
ALTER TABLESPACE TBS_OFFLINE_PRD READ ONLY;

ALTER TABLESPACE TBS_REP_SCHEDULAR READ ONLY;
ALTER TABLESPACE FCCREP READ ONLY;
ALTER TABLESPACE AUDIT_AUX READ ONLY;
