alter session set nls_date_format='YY-MM-DD:hh24:mi:ss';

select sysdate from dual;

alter session set current_schema=SPNLIVE;
ALTER SESSION FORCE PARALLEL DML PARALLEL 32;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 32;
set timing on
exec DBMS_MVIEW.REFRESH('SPNLIVE.M_ACVW_BALANCE_RECON_NEW','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.TMP_ACVW_GL_BAL','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.M_ACVW_GL_BAL','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.TMP_CL_ACCR_MAININT','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.TMP_CL_ACCR_CONTINT','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.M_CUSTACC_ACLASS_MAPPING','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.M_FINAL_PAYMENT_DATA','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.SPN_NON_STAFF_INT','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.SPN_ACCLAS_UPD_INT','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.M_CONT_INT_CALC','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.T_BRANCH_LOG','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.M_DAILY_LOG_19APR','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.M_SPNPLC_LIAB','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.M_ACC_BAL_STATUS','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.M_CLVW_CONT_INT_REVR','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);
exec DBMS_MVIEW.REFRESH('SPNLIVE.ICMW_MJB_ACQUIRED','CF','',TRUE,FALSE, 0,0,0,FALSE,FALSE);

select sysdate from dual;
